// @generated by protoc-gen-connect-web v0.8.6 with parameter "import_extension=.js"
// @generated from file mediafile/v1/mediafile.proto (package mediafile.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetCamerasRequest, GetCamerasResponse, GetConfigRequest, GetConfigResponse, GetLogRequest, GetLogsResponse, GetPhotosRequest, GetPhotosResponse, MovePhotosRequest, MovePhotosResponse, SetConfigRequest, SetConfigResponse } from "./mediafile_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * 
 *
 * @generated from service mediafile.v1.MediafileService
 */
export declare const MediafileService: {
  readonly typeName: "mediafile.v1.MediafileService",
  readonly methods: {
    /**
     * コンフィギュレーションを取得します。
     *
     * @generated from rpc mediafile.v1.MediafileService.SetConfig
     */
    readonly setConfig: {
      readonly name: "SetConfig",
      readonly I: typeof SetConfigRequest,
      readonly O: typeof SetConfigResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * コンフィギュレーションを設定します。
     *
     * @generated from rpc mediafile.v1.MediafileService.GetConfig
     */
    readonly getConfig: {
      readonly name: "GetConfig",
      readonly I: typeof GetConfigRequest,
      readonly O: typeof GetConfigResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * 写真情報を取得します。
     *
     * @generated from rpc mediafile.v1.MediafileService.GetPhotos
     */
    readonly getPhotos: {
      readonly name: "GetPhotos",
      readonly I: typeof GetPhotosRequest,
      readonly O: typeof GetPhotosResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * 写真を移動します。
     *
     * @generated from rpc mediafile.v1.MediafileService.MovePhotos
     */
    readonly movePhotos: {
      readonly name: "MovePhotos",
      readonly I: typeof MovePhotosRequest,
      readonly O: typeof MovePhotosResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * カメラ情報を取得します。
     *
     * @generated from rpc mediafile.v1.MediafileService.GetCameras
     */
    readonly getCameras: {
      readonly name: "GetCameras",
      readonly I: typeof GetCamerasRequest,
      readonly O: typeof GetCamerasResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * ログを取得します。
     *
     * @generated from rpc mediafile.v1.MediafileService.GetLogs
     */
    readonly getLogs: {
      readonly name: "GetLogs",
      readonly I: typeof GetLogRequest,
      readonly O: typeof GetLogsResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

