// @generated by protoc-gen-connect-web v0.8.6 with parameter "import_extension=.js"
// @generated from file mediafile/v1/mediafile.proto (package mediafile.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetCamerasRequest, GetCamerasResponse, GetLogRequest, GetLogResponse, GetPhotosRequest, GetPhotosResponse, GetPhotoSubFoldersRequest, GetPhotoSubFoldersResponse, LoadCameraCacheRequest, LoadCameraCacheResponse, LoadLogRequest, LoadLogResponse, LoadPhotoCacheRequest, LoadPhotoCacheResponse, MovePhotosRequest, MovePhotosResponse, ReadConfigRequest, ReadConfigResponse, SaveCameraCacheRequest, SaveCameraCacheResponse, SaveLogRequest, SaveLogResponse, SavePhotoCacheRequest, SavePhotoCacheResponse, WriteConfigRequest, WriteConfigResponse } from "./mediafile_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * 
 *
 * @generated from service mediafile.v1.MediafileService
 */
export declare const MediafileService: {
  readonly typeName: "mediafile.v1.MediafileService",
  readonly methods: {
    /**
     * コンフィギュレーションを読み込みます。
     *
     * @generated from rpc mediafile.v1.MediafileService.ReadConfig
     */
    readonly readConfig: {
      readonly name: "ReadConfig",
      readonly I: typeof ReadConfigRequest,
      readonly O: typeof ReadConfigResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * コンフィギュレーションを保存します。
     *
     * @generated from rpc mediafile.v1.MediafileService.WriteConfig
     */
    readonly writeConfig: {
      readonly name: "WriteConfig",
      readonly I: typeof WriteConfigRequest,
      readonly O: typeof WriteConfigResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * 写真のキャッシュ情報を保存します。
     *
     * @generated from rpc mediafile.v1.MediafileService.SavePhotoCache
     */
    readonly savePhotoCache: {
      readonly name: "SavePhotoCache",
      readonly I: typeof SavePhotoCacheRequest,
      readonly O: typeof SavePhotoCacheResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * 写真のキャッシュ情報を読み込みます。
     *
     * @generated from rpc mediafile.v1.MediafileService.LoadPhotoCache
     */
    readonly loadPhotoCache: {
      readonly name: "LoadPhotoCache",
      readonly I: typeof LoadPhotoCacheRequest,
      readonly O: typeof LoadPhotoCacheResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * photo_folder以下のディレクトリを取得します。
     *
     * @generated from rpc mediafile.v1.MediafileService.GetPhotoSubFolders
     */
    readonly getPhotoSubFolders: {
      readonly name: "GetPhotoSubFolders",
      readonly I: typeof GetPhotoSubFoldersRequest,
      readonly O: typeof GetPhotoSubFoldersResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * カメラのキャッシュ情報を保存します。
     *
     * @generated from rpc mediafile.v1.MediafileService.SaveCameraCache
     */
    readonly saveCameraCache: {
      readonly name: "SaveCameraCache",
      readonly I: typeof SaveCameraCacheRequest,
      readonly O: typeof SaveCameraCacheResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * カメラのキャッシュ情報を読み込みます。
     *
     * @generated from rpc mediafile.v1.MediafileService.LoadCameraCache
     */
    readonly loadCameraCache: {
      readonly name: "LoadCameraCache",
      readonly I: typeof LoadCameraCacheRequest,
      readonly O: typeof LoadCameraCacheResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * ログを存します。
     *
     * @generated from rpc mediafile.v1.MediafileService.SaveLog
     */
    readonly saveLog: {
      readonly name: "SaveLog",
      readonly I: typeof SaveLogRequest,
      readonly O: typeof SaveLogResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * ログを読み込みます。
     *
     * @generated from rpc mediafile.v1.MediafileService.LoadLog
     */
    readonly loadLog: {
      readonly name: "LoadLog",
      readonly I: typeof LoadLogRequest,
      readonly O: typeof LoadLogResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * 写真情報を取得します。
     *
     * @generated from rpc mediafile.v1.MediafileService.GetPhotos
     */
    readonly getPhotos: {
      readonly name: "GetPhotos",
      readonly I: typeof GetPhotosRequest,
      readonly O: typeof GetPhotosResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * 写真を移動します。
     *
     * @generated from rpc mediafile.v1.MediafileService.MovePhotos
     */
    readonly movePhotos: {
      readonly name: "MovePhotos",
      readonly I: typeof MovePhotosRequest,
      readonly O: typeof MovePhotosResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * カメラ情報を取得します。
     *
     * @generated from rpc mediafile.v1.MediafileService.GetCameras
     */
    readonly getCameras: {
      readonly name: "GetCameras",
      readonly I: typeof GetCamerasRequest,
      readonly O: typeof GetCamerasResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * ログを取得します。
     *
     * @generated from rpc mediafile.v1.MediafileService.GetLog
     */
    readonly getLog: {
      readonly name: "GetLog",
      readonly I: typeof GetLogRequest,
      readonly O: typeof GetLogResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

