// @generated by protoc-gen-connect-web v0.8.6 with parameter "import_extension=.js"
// @generated from file mediafile/v1/mediafile.proto (package mediafile.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetCamerasRequest, GetCamerasResponse, GetConfigRequest, GetConfigResponse, GetLogRequest, GetLogsResponse, GetPhotosRequest, GetPhotosResponse, MovePhotosRequest, MovePhotosResponse, SetConfigRequest, SetConfigResponse } from "./mediafile_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * 
 *
 * @generated from service mediafile.v1.MediafileService
 */
export const MediafileService = {
  typeName: "mediafile.v1.MediafileService",
  methods: {
    /**
     * コンフィギュレーションを取得します。
     *
     * @generated from rpc mediafile.v1.MediafileService.SetConfig
     */
    setConfig: {
      name: "SetConfig",
      I: SetConfigRequest,
      O: SetConfigResponse,
      kind: MethodKind.Unary,
    },
    /**
     * コンフィギュレーションを設定します。
     *
     * @generated from rpc mediafile.v1.MediafileService.GetConfig
     */
    getConfig: {
      name: "GetConfig",
      I: GetConfigRequest,
      O: GetConfigResponse,
      kind: MethodKind.Unary,
    },
    /**
     * 写真情報を取得します。
     *
     * @generated from rpc mediafile.v1.MediafileService.GetPhotos
     */
    getPhotos: {
      name: "GetPhotos",
      I: GetPhotosRequest,
      O: GetPhotosResponse,
      kind: MethodKind.Unary,
    },
    /**
     * 写真を移動します。
     *
     * @generated from rpc mediafile.v1.MediafileService.MovePhotos
     */
    movePhotos: {
      name: "MovePhotos",
      I: MovePhotosRequest,
      O: MovePhotosResponse,
      kind: MethodKind.Unary,
    },
    /**
     * カメラ情報を取得します。
     *
     * @generated from rpc mediafile.v1.MediafileService.GetCameras
     */
    getCameras: {
      name: "GetCameras",
      I: GetCamerasRequest,
      O: GetCamerasResponse,
      kind: MethodKind.Unary,
    },
    /**
     * ログを取得します。
     *
     * @generated from rpc mediafile.v1.MediafileService.GetLogs
     */
    getLogs: {
      name: "GetLogs",
      I: GetLogRequest,
      O: GetLogsResponse,
      kind: MethodKind.Unary,
    },
  }
};

