// @generated by protoc-gen-connect-web v0.8.6 with parameter "import_extension=.js"
// @generated from file v1/mediapath.proto (package mediapath.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetCamerasRequest, GetCamerasResponse, GetLogRequest, GetLogResponse, GetPhotosRequest, GetPhotosResponse, LoadCameraCacheRequest, LoadCameraCacheResponse, LoadLogRequest, LoadLogResponse, LoadPhotoCacheRequest, LoadPhotoCacheResponse, MovePhotosRequest, MovePhotosResponse, ReadConfigRequest, ReadConfigResponse, ReadFolderRequest, ReadFolderResponse, SaveCameraCacheRequest, SaveCameraCacheResponse, SaveLogRequest, SaveLogResponse, SavePhotoCacheRequest, SavePhotoCacheResponse, WriteConfigRequest, WriteConfigResponse } from "./mediapath_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * 
 *
 * @generated from service mediapath.v1.MediapathService
 */
export declare const MediapathService: {
  readonly typeName: "mediapath.v1.MediapathService",
  readonly methods: {
    /**
     * 
     *
     * @generated from rpc mediapath.v1.MediapathService.ReadFolder
     */
    readonly readFolder: {
      readonly name: "ReadFolder",
      readonly I: typeof ReadFolderRequest,
      readonly O: typeof ReadFolderResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * コンフィギュレーションを読み込みます。
     *
     * @generated from rpc mediapath.v1.MediapathService.ReadConfig
     */
    readonly readConfig: {
      readonly name: "ReadConfig",
      readonly I: typeof ReadConfigRequest,
      readonly O: typeof ReadConfigResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * コンフィギュレーションを保存します。
     *
     * @generated from rpc mediapath.v1.MediapathService.WriteConfig
     */
    readonly writeConfig: {
      readonly name: "WriteConfig",
      readonly I: typeof WriteConfigRequest,
      readonly O: typeof WriteConfigResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * 写真のキャッシュ情報を保存します。
     *
     * @generated from rpc mediapath.v1.MediapathService.SavePhotoCache
     */
    readonly savePhotoCache: {
      readonly name: "SavePhotoCache",
      readonly I: typeof SavePhotoCacheRequest,
      readonly O: typeof SavePhotoCacheResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * 写真のキャッシュ情報を読み込みます。
     *
     * @generated from rpc mediapath.v1.MediapathService.LoadPhotoCache
     */
    readonly loadPhotoCache: {
      readonly name: "LoadPhotoCache",
      readonly I: typeof LoadPhotoCacheRequest,
      readonly O: typeof LoadPhotoCacheResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * カメラのキャッシュ情報を保存します。
     *
     * @generated from rpc mediapath.v1.MediapathService.SaveCameraCache
     */
    readonly saveCameraCache: {
      readonly name: "SaveCameraCache",
      readonly I: typeof SaveCameraCacheRequest,
      readonly O: typeof SaveCameraCacheResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * カメラのキャッシュ情報を読み込みます。
     *
     * @generated from rpc mediapath.v1.MediapathService.LoadCameraCache
     */
    readonly loadCameraCache: {
      readonly name: "LoadCameraCache",
      readonly I: typeof LoadCameraCacheRequest,
      readonly O: typeof LoadCameraCacheResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * ログを存します。
     *
     * @generated from rpc mediapath.v1.MediapathService.SaveLog
     */
    readonly saveLog: {
      readonly name: "SaveLog",
      readonly I: typeof SaveLogRequest,
      readonly O: typeof SaveLogResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * ログを読み込みます。
     *
     * @generated from rpc mediapath.v1.MediapathService.LoadLog
     */
    readonly loadLog: {
      readonly name: "LoadLog",
      readonly I: typeof LoadLogRequest,
      readonly O: typeof LoadLogResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * 写真情報を取得します。
     *
     * @generated from rpc mediapath.v1.MediapathService.GetPhotos
     */
    readonly getPhotos: {
      readonly name: "GetPhotos",
      readonly I: typeof GetPhotosRequest,
      readonly O: typeof GetPhotosResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * 写真を移動します。
     *
     * @generated from rpc mediapath.v1.MediapathService.MovePhotos
     */
    readonly movePhotos: {
      readonly name: "MovePhotos",
      readonly I: typeof MovePhotosRequest,
      readonly O: typeof MovePhotosResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * カメラ情報を取得します。
     *
     * @generated from rpc mediapath.v1.MediapathService.GetCameras
     */
    readonly getCameras: {
      readonly name: "GetCameras",
      readonly I: typeof GetCamerasRequest,
      readonly O: typeof GetCamerasResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * ログを取得します。
     *
     * @generated from rpc mediapath.v1.MediapathService.GetLog
     */
    readonly getLog: {
      readonly name: "GetLog",
      readonly I: typeof GetLogRequest,
      readonly O: typeof GetLogResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

