// @generated by protoc-gen-es v2.2.3 with parameter "import_extension=.js"
// @generated from file v1/utils.proto (package utils.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file v1/utils.proto.
 */
export const file_v1_utils = /*@__PURE__*/
  fileDesc("Cg52MS91dGlscy5wcm90bxIIdXRpbHMudjEiQgoHSW5zdGFudBIPCgdzZWNvbmRzGAEgASgDEg0KBW5hbm9zGAIgASgNEhcKD3RpbWV6b25lX29mZnNldBgDIAEoBUJbCgxjb20udXRpbHMudjFCClV0aWxzUHJvdG9QAaICA1VYWKoCCFV0aWxzLlYxygIIVXRpbHNcVjHiAhRVdGlsc1xWMVxHUEJNZXRhZGF0YeoCCVV0aWxzOjpWMWIGcHJvdG8z");

/**
 * Describes the message utils.v1.Instant.
 * Use `create(InstantSchema)` to create a new message.
 */
export const InstantSchema = /*@__PURE__*/
  messageDesc(file_v1_utils, 0);

