// @generated by protoc-gen-es v2.2.3 with parameter "import_extension=.js"
// @generated from file v1/utils.proto (package utils.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file v1/utils.proto.
 */
export declare const file_v1_utils: GenFile;

/**
 * タイムゾーン保持可能な日時メッセージです。
 *
 * @generated from message utils.v1.Instant
 */
export declare type Instant = Message<"utils.v1.Instant"> & {
  /**
   * 1970/1/1 00:00:00からの秒数
   *
   * @generated from field: int64 seconds = 1;
   */
  seconds: bigint;

  /**
   * 秒未満のナノ秒
   *
   * @generated from field: uint32 nanos = 2;
   */
  nanos: number;

  /**
   * タイムゾーンオフセット（秒単位）
   *
   * @generated from field: int32 timezone_offset = 3;
   */
  timezoneOffset: number;
};

/**
 * Describes the message utils.v1.Instant.
 * Use `create(InstantSchema)` to create a new message.
 */
export declare const InstantSchema: GenMessage<Instant>;

